packages:
  - 'docs'
  - 'packages/*'
  - '!packages/nuxt'
  - '!packages/__legacy__'
  - 'samples/*'
  - '!samples/__legacy__/*'
  - '!samples/teamspace-nextjs'

catalog:
  '@wso2/eslint-plugin': 'git+https://github.com/brionmario/wso2-ui-configs.git#a1fc6eb570653c999828aea9f5027cba06af4391&path:packages/eslint-plugin'
  '@wso2/prettier-config': 'git+https://github.com/brionmario/wso2-ui-configs.git#a1fc6eb570653c999828aea9f5027cba06af4391&path:packages/prettier-config'
  '@wso2/stylelint-config': 'git+https://github.com/brionmario/wso2-ui-configs.git#a1fc6eb570653c999828aea9f5027cba06af4391&path:packages/stylelint-config'
